# Generated by Django 6.0.5 on 2026-06-17 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RouteHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_location_name', models.CharField(blank=True, max_length=255, null=True)),
                ('start_lat', models.FloatField()),
                ('start_lng', models.FloatField()),
                ('end_location_name', models.CharField(blank=True, max_length=255, null=True)),
                ('end_lat', models.FloatField()),
                ('end_lng', models.FloatField()),
                ('distance_km', models.FloatField(default=0.0)),
                ('nodes_traversed', models.IntegerField(default=0)),
                ('fuel_saved_liters', models.FloatField(default=0.0)),
                ('co2_prevented_kg', models.FloatField(default=0.0)),
                ('traffic_applied', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Route Histories',
                'ordering': ['-created_at'],
            },
        ),
    ]
