# Generated by Django 6.0.5 on 2026-06-18 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('traffic_multiplier', models.FloatField(default=10.0, help_text='Penalty applied to road segments with live traffic jams')),
                ('surface_multiplier', models.FloatField(default=5.0, help_text='Penalty applied to unpaved roads')),
                ('restricted_multiplier', models.FloatField(default=100.0, help_text='Penalty applied to restricted access roads')),
                ('base_fuel_consumption', models.FloatField(default=8.0, help_text='Base fuel consumption in Liters per 100km')),
                ('eco_efficiency_gain', models.FloatField(default=20.0, help_text='Percentage of fuel saved on eco routes (%)')),
            ],
            options={
                'verbose_name_plural': 'System Settings',
            },
        ),
    ]
