# Generated by Django 6.0.5 on 2026-06-18 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_routehistory_user_directmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoadModifier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modifier_type', models.CharField(choices=[('closure', 'Road Closed'), ('traffic', 'High Traffic')], max_length=20)),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
                ('radius_meters', models.FloatField(default=50.0)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
